type Post {
  id: ID!
  title: String
  content: String
  image: String
  tag: String
  lat: String
  lng: String
  uid: String
  createdAt: String!
  likes: [Like]
  comments: [Comment]
  reports: [Report]
  accomplished: [Status]
}

type Like {
  parentId: String
  like: Int
  dislike: Int
}

type Comment {
  id: ID
  content: String
  answers: [Answer]
}

type Answer {
  id: ID
  content: String
}

type Report {
  id: ID
  type: String
  content: String
}

type Status {
  accomplished: Boolean
  like: [Like]
}

type Query {
  getPosts(uid: String): [Post]
}
