type User {
  id: ID
  uid: String
  username: String
  profilPicture: String
  number: Int
  token: String
  error: String
  # posts: [Post]
  email: String
  createdAt: String
  # date: Date
}

type Query {
  getUser: [User]
}
