apiVersion: v1
kind: Service
metadata:
  name: node-civic-app-service-external
spec:
  selector:
    app: node-civic-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: LoadBalancer
